/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_s;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;
   
/**
 *
 * @author neodze
 */
public class Restaurant extends javax.swing.JFrame {
            double firstNum;
            double SecondNum;
            double Result;
            String operations;
            double[] i = new double[5];
    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jbtnPlus = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnMinus = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jtxtDisplay24 = new javax.swing.JButton();
        jbtnMultiple = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtnEquals = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jCheckChickBurger = new javax.swing.JCheckBox();
        jCheckBaconAndCheese = new javax.swing.JCheckBox();
        jCheckChickenBurgerMeal = new javax.swing.JCheckBox();
        jtxtChickBuerger = new javax.swing.JTextField();
        jtextChickenBurgerMeal = new javax.swing.JTextField();
        jtxtBaconAndCheese = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckTax = new javax.swing.JCheckBox();
        JchckHomeDelivery = new javax.swing.JCheckBox();
        JCmdDrinks = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCostOfDrinks = new javax.swing.JTextField();
        JtxtHomeDelivery = new javax.swing.JTextField();
        jCostOfMeal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jcmbCurrency = new javax.swing.JComboBox<>();
        jtxtConvert = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        jPanel9 = new javax.swing.JPanel();
        Convert = new java.awt.Button();
        jtxtCurrencyResult = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jbuttoneciept = new java.awt.Button();
        jbuttonReset = new java.awt.Button();
        jbuttonExit = new java.awt.Button();
        jbuttonTotal = new java.awt.Button();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JTextField();
        jTotal = new javax.swing.JTextField();
        jSubTotal = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.setToolTipText("");
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });

        jbtnPlus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.setToolTipText("");
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });

        jbtnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnClear.setText("C");
        jbtnClear.setToolTipText("");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMinus.setText("-");
        jbtnMinus.setToolTipText("");
        jbtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMinusActionPerformed(evt);
            }
        });

        jbtnBack.setFont(new java.awt.Font("Webdings", 1, 18)); // NOI18N
        jbtnBack.setText("🡨");
        jbtnBack.setToolTipText("");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jtxtDisplay24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDisplay24.setText("+/-");
        jtxtDisplay24.setToolTipText("");
        jtxtDisplay24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplay24ActionPerformed(evt);
            }
        });

        jbtnMultiple.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMultiple.setText("*");
        jbtnMultiple.setToolTipText("");
        jbtnMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultipleActionPerformed(evt);
            }
        });

        jbtnDivide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDivide.setText("/");
        jbtnDivide.setToolTipText("");
        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivideActionPerformed(evt);
            }
        });

        jbtnEquals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnEquals.setText("=");
        jbtnEquals.setToolTipText("");
        jbtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualsActionPerformed(evt);
            }
        });

        jbtnDot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.setToolTipText("");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn0.setText("0");
        jBtn0.setToolTipText("");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn7.setText("7");
        jbtn7.setToolTipText("");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setToolTipText("");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn1.setText("1");
        jbtn1.setToolTipText("");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setToolTipText("");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setToolTipText("");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setToolTipText("");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn2.setText("2");
        jbtn2.setToolTipText("");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setToolTipText("");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn3.setText("3");
        jbtn3.setToolTipText("");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtDisplay)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtDisplay24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDisplay24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1607, 1607, 1607))
        );

        jTabbedPane1.addTab("Calculator", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Recept", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jCheckChickBurger.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckChickBurger.setText("Chicken Burger");
        jCheckChickBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckChickBurgerMouseClicked(evt);
            }
        });
        jCheckChickBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckChickBurgerActionPerformed(evt);
            }
        });

        jCheckBaconAndCheese.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBaconAndCheese.setText("bacon and cheese burger");
        jCheckBaconAndCheese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBaconAndCheeseMouseClicked(evt);
            }
        });
        jCheckBaconAndCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBaconAndCheeseActionPerformed(evt);
            }
        });

        jCheckChickenBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckChickenBurgerMeal.setText("Chicken Burger meal");
        jCheckChickenBurgerMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckChickenBurgerMealMouseClicked(evt);
            }
        });
        jCheckChickenBurgerMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckChickenBurgerMealActionPerformed(evt);
            }
        });

        jtxtChickBuerger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtChickBuerger.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtChickBuerger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtChickBuerger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickBuergerActionPerformed(evt);
            }
        });

        jtextChickenBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtextChickenBurgerMeal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtextChickenBurgerMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtBaconAndCheese.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtBaconAndCheese.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtBaconAndCheese.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Drinks");

        jCheckTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckTax.setText("Tax");
        jCheckTax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckTaxMouseClicked(evt);
            }
        });
        jCheckTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTaxActionPerformed(evt);
            }
        });

        JchckHomeDelivery.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JchckHomeDelivery.setText("Home Delivery");
        JchckHomeDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JchckHomeDeliveryMouseClicked(evt);
            }
        });
        JchckHomeDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JchckHomeDeliveryActionPerformed(evt);
            }
        });

        JCmdDrinks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JCmdDrinks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "Tea", "Ice_Tea", "Coffee", "Cola", "Coke", " " }));
        JCmdDrinks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCmdDrinksMouseClicked(evt);
            }
        });
        JCmdDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCmdDrinksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBaconAndCheese)
                    .addComponent(jCheckChickenBurgerMeal)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckTax)
                    .addComponent(jCheckChickBurger))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JchckHomeDelivery)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtChickBuerger, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtextChickenBurgerMeal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtBaconAndCheese, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JCmdDrinks, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckChickBurger)
                    .addComponent(jtxtChickBuerger, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckChickenBurgerMeal)
                    .addComponent(jtextChickenBurgerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBaconAndCheese)
                    .addComponent(jtxtBaconAndCheese, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JCmdDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckTax)
                    .addComponent(JchckHomeDelivery))
                .addGap(18, 18, 18))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cost Of Drinks");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cost Of Meal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cost Of Delivery");

        jCostOfDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCostOfDrinks.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCostOfDrinks.setText("0");
        jCostOfDrinks.setToolTipText("");
        jCostOfDrinks.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jCostOfDrinks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCostOfDrinksMouseClicked(evt);
            }
        });
        jCostOfDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCostOfDrinksActionPerformed(evt);
            }
        });

        JtxtHomeDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JtxtHomeDelivery.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JtxtHomeDelivery.setText("0");

        jCostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCostOfMeal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCostOfMeal.setText("0");
        jCostOfMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCostOfMealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JtxtHomeDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtxtHomeDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jcmbCurrency.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcmbCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "USA", "Nigeria", "Kenyan", "Canada", "Brazil", "Indonesia", "Philippine", " ", " " }));
        jcmbCurrency.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jcmbCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbCurrencyActionPerformed(evt);
            }
        });

        jtxtConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        button1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button1.setLabel("Close");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        Convert.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Convert.setLabel("Convert");
        Convert.setName(""); // NOI18N
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });

        jtxtCurrencyResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCurrencyResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtCurrencyResult.setBorder(new javax.swing.border.MatteBorder(null));
        jtxtCurrencyResult.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtCurrencyResult.setDoubleBuffered(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCurrencyResult, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtCurrencyResult, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbuttoneciept.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbuttoneciept.setLabel("Reciept");
        jbuttoneciept.setName(""); // NOI18N
        jbuttoneciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonecieptActionPerformed(evt);
            }
        });

        jbuttonReset.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbuttonReset.setLabel("Reset");
        jbuttonReset.setName(""); // NOI18N
        jbuttonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonResetMouseClicked(evt);
            }
        });
        jbuttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonResetActionPerformed(evt);
            }
        });

        jbuttonExit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbuttonExit.setLabel("Exit");
        jbuttonExit.setName(""); // NOI18N
        jbuttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonExitActionPerformed(evt);
            }
        });

        jbuttonTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbuttonTotal.setLabel("Total");
        jbuttonTotal.setName(""); // NOI18N
        jbuttonTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonTotalMouseClicked(evt);
            }
        });
        jbuttonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jbuttonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jbuttoneciept, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jbuttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jbuttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttoneciept, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Sub Total:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Tax:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Total:");

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtTax.setText("0");
        jtxtTax.setToolTipText("");
        jtxtTax.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });

        jTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTotal.setText("0");
        jTotal.setToolTipText("");
        jTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });

        jSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jSubTotal.setText("0");
        jSubTotal.setToolTipText("");
        jSubTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTextField2.setText("Restaurant Manegment System");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckChickBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckChickBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckChickBurgerActionPerformed

    private void jCheckBaconAndCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBaconAndCheeseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBaconAndCheeseActionPerformed

    private void jCheckChickenBurgerMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckChickenBurgerMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckChickenBurgerMealActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
            String EnterNumber = jtxtDisplay.getText() + jbtn7.getText();
            jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String EnterNumber = jtxtDisplay.getText() + jbtn8.getText();
            jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
            String EnterNumber = jtxtDisplay.getText() + jbtn9.getText();
            jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String EnterNumber = jtxtDisplay.getText() + jbtn4.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String EnterNumber = jtxtDisplay.getText() + jbtn5.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String EnterNumber = jtxtDisplay.getText() + jbtn6.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
       String EnterNumber = jtxtDisplay.getText() + jbtn1.getText();
       jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
      String EnterNumber = jtxtDisplay.getText() + jbtn2.getText();
      jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
      String EnterNumber = jtxtDisplay.getText() + jbtn3.getText();
      jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
            String EnterNumber = jtxtDisplay.getText() + jBtn0.getText();
            jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
                jtxtDisplay.setText(null);
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
             String backspace = "";
                if( jtxtDisplay.getText().length() > 0 ){ 
                    StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
                    strB.deleteCharAt(jtxtDisplay.getText().length() - 1);
                    backspace = strB.toString();
                    jtxtDisplay.setText(backspace);
                }
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
                firstNum =  Double.parseDouble(jtxtDisplay.getText());
                jtxtDisplay.setText("");
                operations = "+";
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed
                firstNum =  Double.parseDouble(jtxtDisplay.getText());
                jtxtDisplay.setText("");
                operations = "/";
    }//GEN-LAST:event_jbtnDivideActionPerformed

    private void jbtnMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultipleActionPerformed
                firstNum =  Double.parseDouble(jtxtDisplay.getText());
                jtxtDisplay.setText("");
                operations = "*";
    }//GEN-LAST:event_jbtnMultipleActionPerformed

    private void jbtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMinusActionPerformed
                firstNum =  Double.parseDouble(jtxtDisplay.getText());
                jtxtDisplay.setText("");
                operations = "-";
    }//GEN-LAST:event_jbtnMinusActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
                jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText());
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jtxtDisplay24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplay24ActionPerformed
                 double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
                 ops = ops * (-1);
                 jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jtxtDisplay24ActionPerformed

    private void jbtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualsActionPerformed
                String answer;
                SecondNum = Double.parseDouble(jtxtDisplay.getText());
                if(operations == "+"){
                    
                    Result = firstNum + SecondNum;
                    answer = String.format("%.2f",Result);
                    jtxtDisplay.setText(answer);
                }
                
                else if(operations == "-"){
                    Result = firstNum - SecondNum;
                    answer = String.format("%.2f",Result);
                    jtxtDisplay.setText(answer);
                }
                
                 else if(operations == "/"){
                    Result = firstNum / SecondNum;
                    answer = String.format("%.2f",Result);
                    jtxtDisplay.setText(answer);
                }
                
                 else if(operations == "*"){
                    Result = firstNum * SecondNum;
                    answer = String.format("%.2f",Result);
                    jtxtDisplay.setText(answer);
                }
                
                  else if(operations == "%"){
                    Result = firstNum % SecondNum;
                    answer = String.format("%.2f",Result);
                    jtxtDisplay.setText(answer);
                }
    }//GEN-LAST:event_jbtnEqualsActionPerformed

    private void jcmbCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbCurrencyActionPerformed

    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertActionPerformed
           double Nigerian_Naira=2,Kenyan_Shiling=1.9,Us_Dollar = 1.5, Canadian_Dollar = 3.4, 
                  Brazilian_Real = 1.2, Indian_Rupee = 3.1, Philipine_Peso = 1.4;
           String cConvert = null;
            double British_Pound = Double.parseDouble(jtxtConvert.getText());
                  if(jcmbCurrency.getSelectedItem().equals("Nigeria")){
                  cConvert = String.format("%2f", British_Pound * Nigerian_Naira);
                }
                  if(jcmbCurrency.getSelectedItem().equals("Kenyan")){
                   cConvert = String.format("%2f", British_Pound * Kenyan_Shiling);
                }
                  if(jcmbCurrency.getSelectedItem().equals("USA")){
                   cConvert = String.format("%2f", British_Pound * Us_Dollar);
                }
                  if(jcmbCurrency.getSelectedItem().equals("Canada")){
                   cConvert = String.format("%2f", British_Pound * Canadian_Dollar);
                }
                  if(jcmbCurrency.getSelectedItem().equals("Brazil")){
                   cConvert = String.format("%2f", British_Pound * Brazilian_Real);
                }
                  if(jcmbCurrency.getSelectedItem().equals("India")){
                   cConvert = String.format("%2f", British_Pound * Indian_Rupee);
                }
                  if(jcmbCurrency.getSelectedItem().equals("Philipine")){
                   cConvert = String.format("%2f", British_Pound * Philipine_Peso);
                }              
                
                  jtxtCurrencyResult.setText(cConvert); 
    }//GEN-LAST:event_ConvertActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void jCheckTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckTaxActionPerformed

    private void jbuttonecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonecieptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonecieptActionPerformed

    private void jbuttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonResetActionPerformed
            
    }//GEN-LAST:event_jbuttonResetActionPerformed

    private void jbuttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbuttonExitActionPerformed

    private void jbuttonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonTotalActionPerformed
                    
    }//GEN-LAST:event_jbuttonTotalActionPerformed

    private void JCmdDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCmdDrinksActionPerformed
        Double Tea = 1.20, Ice_Tea = 0.90, Coffee = 2.50, Ice_Coffee = 1.10, Cola = 2.10, Coke = 1.60;  
        if(JCmdDrinks.getSelectedItem().equals("Tea")){
           String cTea = String.format("%.2f", Tea);
           jCostOfDrinks.setText(cTea);
        }
        
        if(JCmdDrinks.getSelectedItem().equals("Ice_Tea")){
          String cIce_Tea = String.format("%.2f", Ice_Tea);
          jCostOfDrinks.setText(cIce_Tea);
        }
        
        if(JCmdDrinks.getSelectedItem().equals("Coffee")){
          String cCoffee = String.format("%.2f", Coffee);
          jCostOfDrinks.setText(cCoffee);
        }
        
         if(JCmdDrinks.getSelectedItem().equals("Cola")){
          String cCola = String.format("%.2f", Cola);
          jCostOfDrinks.setText(cCola);
        }
        
         if(JCmdDrinks.getSelectedItem().equals("Coke")){
          String cCoke = String.format("%.2f", Coke);
          jCostOfDrinks.setText(cCoke);
        }
         
          if(JCmdDrinks.getSelectedItem().equals("Choose One...")){
                jCostOfDrinks.setText(null);
                
        }


    }//GEN-LAST:event_JCmdDrinksActionPerformed

    private void jCostOfDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCostOfDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCostOfDrinksActionPerformed

    private void JchckHomeDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JchckHomeDeliveryMouseClicked
                Double iDelivery = 3.39;
                if(JchckHomeDelivery.isSelected()){
                    String pDelivery = String.format("%.2f", iDelivery);
                    JtxtHomeDelivery.setText(pDelivery);
                }else {
                    JtxtHomeDelivery.setText(null);
                }
    }//GEN-LAST:event_JchckHomeDeliveryMouseClicked

    private void JchckHomeDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JchckHomeDeliveryActionPerformed

    }//GEN-LAST:event_JchckHomeDeliveryActionPerformed

    private void jCheckChickBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckChickBurgerMouseClicked
            double cMeal = Double.parseDouble(jCostOfMeal.getText());
            double ChicBurger = Double.parseDouble(jtxtChickBuerger.getText());
            double iChicBurger = 2.39;
            
            if(jCheckChickBurger.isSelected()){
                i[0] = (ChicBurger * iChicBurger) + cMeal; 
                String pMeal = String.format("%.2f",i[0]);
                jCostOfMeal.setText(pMeal);
            }
    }//GEN-LAST:event_jCheckChickBurgerMouseClicked

    private void jCostOfMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCostOfMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCostOfMealActionPerformed

    private void jbuttonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonResetMouseClicked
           jCostOfMeal.setText("0");
           jtxtChickBuerger.setText("0");
           JtxtHomeDelivery.setText("0");
           jtextChickenBurgerMeal.setText("0");
           jtxtBaconAndCheese.setText("0");
           jSubTotal.setText("0");
           jtxtTax.setText("0");
           jTotal.setText("0");
    }//GEN-LAST:event_jbuttonResetMouseClicked

    private void jtxtChickBuergerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickBuergerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickBuergerActionPerformed

    private void jCheckChickenBurgerMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckChickenBurgerMealMouseClicked
            double cMeal = Double.parseDouble(jCostOfMeal.getText());
            double ChicBurgerMeal = Double.parseDouble(jtextChickenBurgerMeal.getText());
            double iChicBurger = 3.49;
            
            if(jCheckChickenBurgerMeal.isSelected()){
                i[1] = (ChicBurgerMeal * iChicBurger) + cMeal; 
                String pMeal = String.format("%.2f",i[1]);
                jCostOfMeal.setText(pMeal);
            }
    }//GEN-LAST:event_jCheckChickenBurgerMealMouseClicked

    private void jCheckBaconAndCheeseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBaconAndCheeseMouseClicked
            double cMeal = Double.parseDouble(jCostOfMeal.getText());
            double BackonAndCheese = Double.parseDouble(jtxtBaconAndCheese.getText());
            double iChicBurger = 5;
            
            if(jCheckBaconAndCheese.isSelected()){
                i[1] = (BackonAndCheese * iChicBurger) + cMeal; 
                String pMeal = String.format("%.2f",i[1]);
                jCostOfMeal.setText(pMeal);
            }
    }//GEN-LAST:event_jCheckBaconAndCheeseMouseClicked

    private void jbuttonTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonTotalMouseClicked
          
            double cTotal1 = Double.parseDouble(jCostOfDrinks.getText());
            double cTotal2 = Double.parseDouble(jCostOfMeal.getText());
            double cTotal3 = Double.parseDouble(JtxtHomeDelivery.getText());
            double cTotal4 = Double.parseDouble(jtxtTax.getText());
            
            double subTotal = cTotal1 + cTotal2 + cTotal3;
            String isubTotal = String.format("% 2f",subTotal);
            jSubTotal.setText(isubTotal);
            
            double AllTotal = cTotal1 + cTotal2 + cTotal3 + cTotal4;
            String iTotal = String.format("% 2f",AllTotal);
            jTotal.setText(iTotal);
            
            String iTaxTotal = String.format("%.2f",cTotal4);
            jtxtTax.setText(iTaxTotal);
    }//GEN-LAST:event_jbuttonTotalMouseClicked

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTotalActionPerformed

    private void jSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSubTotalActionPerformed

    private void jCheckTaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckTaxMouseClicked

            double cTotal1 = Double.parseDouble(jCostOfDrinks.getText());
            double cTotal2 = Double.parseDouble(jCostOfMeal.getText());
            double cTotal3 = Double.parseDouble(JtxtHomeDelivery.getText());
            double cTotal4 = Double.parseDouble(jtxtTax.getText());
              
            if(jCheckTax.isSelected()){
                double Tax = ((cTotal1 + cTotal2 + cTotal3)/100)*20;
                String sTax = String.format("% 2f",Tax);
                jtxtTax.setText(sTax);
            }
    }//GEN-LAST:event_jCheckTaxMouseClicked

    private void jCostOfDrinksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCostOfDrinksMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCostOfDrinksMouseClicked

    private void JCmdDrinksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCmdDrinksMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JCmdDrinksMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Convert;
    private javax.swing.JComboBox<String> JCmdDrinks;
    private javax.swing.JCheckBox JchckHomeDelivery;
    private javax.swing.JTextField JtxtHomeDelivery;
    private java.awt.Button button1;
    private javax.swing.JButton jBtn0;
    private javax.swing.JCheckBox jCheckBaconAndCheese;
    private javax.swing.JCheckBox jCheckChickBurger;
    private javax.swing.JCheckBox jCheckChickenBurgerMeal;
    private javax.swing.JCheckBox jCheckTax;
    private javax.swing.JTextField jCostOfDrinks;
    private javax.swing.JTextField jCostOfMeal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jSubTotal;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTotal;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnEquals;
    private javax.swing.JButton jbtnMinus;
    private javax.swing.JButton jbtnMultiple;
    private javax.swing.JButton jbtnPlus;
    private java.awt.Button jbuttonExit;
    private java.awt.Button jbuttonReset;
    private java.awt.Button jbuttonTotal;
    private java.awt.Button jbuttoneciept;
    private javax.swing.JComboBox<String> jcmbCurrency;
    private javax.swing.JTextField jtextChickenBurgerMeal;
    private javax.swing.JTextField jtxtBaconAndCheese;
    private javax.swing.JTextField jtxtChickBuerger;
    private javax.swing.JTextField jtxtConvert;
    private javax.swing.JTextField jtxtCurrencyResult;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JButton jtxtDisplay24;
    private javax.swing.JTextField jtxtTax;
    // End of variables declaration//GEN-END:variables
}
